Repository kubereboot/kured, pull requests merged in 2020-11, with the labels that each got.

#217 Clean up deps, update docs to explain state post-210
  DEVELOPMENT.md
  README.md
  go.mod
  go.sum
Labels: dependencies

#238 rename annotation-ttl to lock-ttl in all places, follow-up to #213
  README.md
  charts/kured/README.md
  charts/kured/templates/daemonset.yaml
  charts/kured/values.yaml
Labels: docs, helm-chart

#206 Added support for time wrap in timewindow.Contains
  pkg/timewindow/timewindow.go
  pkg/timewindow/timewindow_test.go
Labels: bug

#212 GH-125, add additional parameters for the drain/reboot slack message template
  DEVELOPMENT.md
  README.md
  charts/kured/Chart.yaml
  charts/kured/README.md
  charts/kured/templates/daemonset.yaml
  charts/kured/values.minikube.yaml
  charts/kured/values.yaml
  cmd/kured/main.go
  kured-ds.yaml
  pkg/notifications/slack/slack.go
Labels: notifications

#183 Add smoke/basic functional test
  .github/kind-cluster.yaml
  .github/workflows/smoke-tests.yml
  tests/kind/create-reboot-sentinels.sh
  tests/kind/follow-coordinated-reboot.sh
Labels: testing

#184 Increase test matrix for smoke tests
  .github/kind-cluster-1.17.yaml
  .github/kind-cluster-1.18.yaml
  .github/kind-cluster-1.19.yaml
  .github/workflows/smoke-tests.yml
Labels: testing

#181 Add manifests testing
  .github/workflows/manifests-tests.yml
Labels: testing

#246 Improve coordinated reboot output
  tests/kind/follow-coordinated-reboot.sh
Labels: build, testing

#249 Add more logs into gates
  tests/kind/follow-coordinated-reboot.sh
Labels: testing

#241 Cleanup github actions
  .github/workflows/chart-lint.yml
  .github/workflows/check-links.yaml
  .github/workflows/go-lint.yaml
  .github/workflows/manifests-tests.yml
  .github/workflows/on-pr-charts.yaml
  .github/workflows/on-pr.yaml
  .github/workflows/on-release.yaml
  .github/workflows/on-tag.yaml
  .github/workflows/periodics-daily.yaml
  .github/workflows/shellcheck.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/stale.yaml
  .github/workflows/vulnerability-scan.yaml
  DEVELOPMENT.md
Labels: build, testing

#255 Merge k8s and go updates
  .circleci/config.yml
  README.md
  charts/kured/templates/clusterrole.yaml
  go.mod
  go.sum
  kured-rbac.yaml
Labels: build
