Repository kubereboot/kured, pull requests merged in 2021-04, with the labels that each got.

#334 Fix invoke reboot for custom commands
  cmd/kured/main.go
Labels: bug

#335 Use chart appVersion as default image-tag
  Makefile
  charts/kured/Chart.yaml
  charts/kured/templates/daemonset.yaml
  charts/kured/values.yaml
Labels: helm-chart

#339 Update github actions
  .github/workflows/on-pr-charts.yaml
  .github/workflows/on-pr.yaml
Labels: testing

#340 Update dev docs
  DEVELOPMENT.md
Labels: docs

#350 update to latest k8s deps of 1.20 branch
  README.md
  go.mod
  go.sum
Labels: dependencies

#355 Reduce false positives
  .github/workflows/on-pr-charts.yaml
Labels: bug, helm-chart, testing

#354 Add prometheus export metrics functional testing
  .github/workflows/on-pr.yaml
  charts/kured/Chart.yaml
  charts/kured/ci/prometheus-values.yaml
  charts/kured/templates/service.yaml
  charts/kured/values.yaml
  tests/kind/test-metrics.sh
Labels: testing
