Repository kubereboot/kured, pull requests merged in 2021-05, with the labels that each got.

#348 Clarify and simplify tests
  .github/workflows/on-pr-charts.yaml
  .github/workflows/on-pr.yaml
  .github/workflows/periodics-daily.yaml
  DEVELOPMENT.md
  Makefile
Labels: testing

#375 update golang.org/x/crypto - break out of #349
  go.mod
  go.sum
Labels: dependencies

#349 Update test matrix to latest 3 sets of k8s releases
  .github/kind-cluster-1.19.yaml
  .github/kind-cluster-1.20.yaml
  .github/kind-cluster-1.21.yaml
  .github/workflows/on-pr-charts.yaml
  .github/workflows/on-pr.yaml
  .github/workflows/periodics-daily.yaml
Labels: testing

#377 Release 1.7.0: Compatibility docs
  README.md
Labels: docs

#338 update chart definition to include --notify-url
  charts/kured/Chart.yaml
  charts/kured/README.md
  charts/kured/templates/daemonset.yaml
  charts/kured/values.minikube.yaml
  charts/kured/values.yaml
Labels: helm-chart

#353 Add lockReleaseDelay parameter to helm chart
  README.md
  charts/kured/Chart.yaml
  charts/kured/README.md
  charts/kured/templates/daemonset.yaml
  charts/kured/values.minikube.yaml
  charts/kured/values.yaml
Labels: helm-chart
