Repository kubereboot/kured, pull requests merged in 2022-09, with the labels that each got.

#631 Update Slack information - point to CNCF Slack.
  MAINTAINERS
  README.md
Labels: community

#637 Add a warning to inform users about move
  README.md
Labels: docs

#638 require DCO from now on
  DCO
  DEVELOPMENT.md
Labels: community

#643 Add footer to README
  README.md
  img/cncf-color.png
Labels: docs

#650 Use github token instead of bot accounts
  .github/workflows/on-main-push.yaml
  .github/workflows/on-tag.yaml
Labels: build
