Repository kubereboot/kured, pull requests merged in 2022-06, with the labels that each got.

#569 Downgrade kind-images for 1.22.x and 1.23.x
  .github/kind-cluster-1.22.yaml
  .github/kind-cluster-1.23.yaml
Labels: build

#496 Added support for multi-arch image build
  .github/workflows/on-main-push.yaml
  .github/workflows/on-tag.yaml
  Makefile
  cmd/kured/Dockerfile.multi
Labels: enhancement, build

#587 added notification when uncordoning
  README.md
  cmd/kured/main.go
Labels: enhancement

#592 add CoC file
  CODE_OF_CONDUCT.md
  README.md
Labels: docs

#589 Updated helm charts with new message template flag
  charts/kured/Chart.yaml
  charts/kured/README.md
  charts/kured/templates/daemonset.yaml
  charts/kured/values.minikube.yaml
  charts/kured/values.yaml
  kured-ds.yaml
Labels: helm-chart
