Repository kubereboot/kured, pull requests merged in 2022-05, with the labels that each got.

#486 retry cordon + drain if fail, keep lock
  cmd/kured/main.go
Labels: enhancement

#539 helm: ensure kured on 1.24 gets the correct toleration
  charts/kured/Chart.yaml
  charts/kured/README.md
  charts/kured/templates/daemonset.yaml
  charts/kured/values.yaml
Labels: helm-chart

#541 Add node labelling
  README.md
  cmd/kured/main.go
Labels: enhancement

#554 Use clean patch to update node labels. Fixes #553
  cmd/kured/main.go
Labels: bug

#552 feat: update kubernetes dependencies
  .github/kind-cluster-1.21.yaml
  .github/kind-cluster-1.22.yaml
  .github/kind-cluster-1.23.yaml
  .github/kind-cluster-1.24.yaml
  .github/workflows/on-pr-charts.yaml
  .github/workflows/on-pr.yaml
  .github/workflows/periodics-daily.yaml
  README.md
  go.mod
  go.sum
  kured-ds.yaml
Labels: enhancement
