Repository kubereboot/kured, pull requests merged in 2022-10, with the labels that each got.

#595 Integrate GoReleaser, Cosign and Syft
  .github/scripts/goreleaser-install.sh
  .github/workflows/on-main-push.yaml
  .github/workflows/on-pr.yaml
  .github/workflows/on-tag.yaml
  .github/workflows/periodics-daily.yaml
  .gitignore
  .goreleaser.yml
  DEVELOPMENT.md
  Dockerfile
  Makefile
  cmd/kured/Dockerfile
  cmd/kured/Dockerfile.multi
Labels: build, security

#662 update meeting day
  README.md
Labels: community

#670 update x/net and x/text to include security fix
  README.md
  go.mod
  go.sum
Labels: dependencies

#682 Move DEV doc to be CONTRIBUTING.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: docs
