Repository kubereboot/kured, pull requests merged in 2023-08, with the labels that each got.

#805 use readOnlyRootFilesystem for manifests
  kured-ds.yaml
Labels: security

#811 Adds new flag --metrics-host
  cmd/kured/main.go
  kured-ds.yaml
Labels: enhancement

#660 Add multiple concurrent node reboot feature
  .github/workflows/on-pr.yaml
  cmd/kured/main.go
  kured-ds.yaml
  pkg/daemonsetlock/daemonsetlock.go
  pkg/daemonsetlock/daemonsetlock_test.go
  tests/kind/follow-coordinated-reboot.sh
Labels: enhancement, keep

#809 Update build-tools
  .github/scripts/goreleaser-install.sh
  .github/workflows/on-main-push.yaml
  .github/workflows/on-tag.yaml
  Makefile
Labels: build

#818 Update to go@1.20, Kubernetes@0.27.4, e2e-test with Kubernetes 1.26-1.28
  .github/kind-cluster-1.25.yaml
  .github/kind-cluster-1.28.yaml
  .github/workflows/on-pr.yaml
  go.mod
  go.sum
Labels: enhancement
